### ISSUE TITLE
Brake spi speed

### ISSUE THREAD

**Issue by bigjohnson** [mtirado1/at89s8252-arduino#1]
Hello,
with my multi kilometers cable the spi speed is too fast, write run but verify fail (the led blink!)
With SPI_CLOCK_DIV128 the program verify work also.
I conseil slowing spi.
Thanks.

**Comment by mtirado1** [comment]
According to the AT89S8252 datasheet:
> The maximum serial clock (SCK) frequency should be less than 1/40 of the crystal frequency (of the chip to be programmed).

This should be added on the README in a future update.
